[settings]
lockfile = true

[env]
TYPST_FONT_PATHS = "{{config_root}}/fonts"
TYPST_INPUT = "main.typ"
TYPST_OUTPUT = "out/main.pdf"

[tools]
typst = "0.15.0"
typstyle = "0.14.4"
tinymist = "0.15.0"

[tasks.build]
run = "typst compile $TYPST_INPUT $TYPST_OUTPUT"

[tasks.watch]
run = "typst watch $TYPST_INPUT $TYPST_OUTPUT"

[tasks.clean]
run = "rm -rf out"

[tasks.format]
run = "typstyle --inplace ."

[tasks."check:format"]
run = "typstyle --check ."

[tasks."check:lint"]
run = 'find . -type f -name "*.typ" -not -path "./out/*" -exec tinymist lint --root . {} \;'
