name: Build Resume

on:
  push:
    branches:
      - main

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Check formatting
        uses: typstyle-rs/typstyle-action@main

  build:
    needs: check-format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install Typst
        uses: typst-community/setup-typst@v5

      - name: Build PDF
        env:
          TYPST_FONT_PATHS: fonts
        run: |-
          typst compile main.typ main.pdf

      - name: Prepare artifact
        id: prep
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs')

            const prefix = '${{ vars.BUILD_OUTPUT_FILE_PREFIX }}'
            const filename = prefix
              ? `${prefix} Resume.pdf`
              : `Resume.pdf`

            fs.renameSync('main.pdf', filename)
            core.setOutput('filename', filename)

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.prep.outputs.filename }}
          path: ${{ steps.prep.outputs.filename }}
