name: Build Resume

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: texlive/texlive:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Build PDF
        run: make all
        env:
          BUILD_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Prepare artifact
        id: prep
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs')

            const nameSlug = 'kutsan-kaplan'
            const shortSha = context.sha.substring(0, 7)
            const filename = `${nameSlug}-resume-${shortSha}.pdf`

            fs.renameSync('dist/main.pdf', filename)
            core.setOutput('filename', filename)

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.prep.outputs.filename }}
          path: ${{ steps.prep.outputs.filename }}
